config/routes.rb
Rails.application.routes.draw do

  

  root 'pages#home'
 
  get :send_request_mail, to: 'posts#send_request_mail', as: :send_request_mail
 
  get    'login'   => 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  get '/showMyPosts' => 'posts#showMyPosts'

  resources :users
  resources :posts
 

end

app/models/post.rb
class Post < ActiveRecord::Base

    belongs_to :user
    validates :title, presence: true, length: {maximum: 100}
    validates :description, presence: true, length: {maximum: 300}

    
    
    def self.search(search)
      if search
        where("title LIKE ?", "%#{search}%") 
        #find(:all, :conditions => ['title ILIKE ?', "%#{search}%"])
      else
        find(:all)
      end
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
    before_action :correct_user,   only: [:edit]
    helper_method :sort_column
    
    def index 
      if params[:search]
        @posts = Post.includes(:user).order(params[:sort]).paginate(page: params[:page], per_page: 5).search(params[:search])
      else
        @posts = Post.all.includes(:user).order(params[:sort]).paginate(page: params[:page], per_page: 5)
      end
    end
    
    def showMyPosts
      #@current_user = User.find(Rails.application.config.current_user.id)
      @posts = current_user.posts.includes(:user).order(params[:sort]).paginate(page: params[:page], per_page: 5)
    end
    
    def new 
        @post = Post.new
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def send_request_mail
      @post = Post.find(params[:id])
      @user = User.find(@post.user_id)
      @current_user = User.find(current_user.id)
      #@current_user = User.find(Rails.application.config.current_user.id)
      
     # if params[:post]
        UserMailer.request_email(@post, @current_user).deliver_now
        UserMailer.confirmation_email(@post, @current_user).deliver_now
        flash[:notice] = "Thank you for helping! An email has been sent to #{@user.name}."
        redirect_to '/posts'
     # end
    end
  
    def create 

      #@current_user = User.find(Rails.application.config.current_user.id)
      @post = current_user.posts.build(post_params)
      
      if @post.save 
        redirect_to '/posts'
      else 
        render 'new' 
      end 
    end
    
    def edit
      @post = Post.find(params[:id])
    end
    
    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(post_params)
        redirect_to @post
      else
        render 'edit'  
      end
    end
    
    def destroy
      Post.find(params[:id]).destroy
      flash[:success] = "Post deleted"
      redirect_to '/showMyPosts'
    end
    
    private
        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
            params.require(:post).permit(:title, :description, :usermyid)
        end

      # Confirms the correct user.
      def correct_user
        @post = Post.find(params[:id])
        redirect_to root_path unless @post.user_id == current_user.id
      end
      
      def sort_column
        #Post.column_names.include?(params[:sort]) ? params[:sort] : nil   
        (params[:sort]) ? params[:sort] : nil   
      end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="page-wrapper">

<h2>Update your Post</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= render 'shared/error_messages' %>
    <%= form_for(@post) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <br> 
      <div class="col-xs-4">
        <%= f.submit "Save changes", class: "btn btn-primary" %>
      </div>
       <br> <br> <br> <br>
      <div><a href="<%= posts_path %>/<%= @post.id %>">Cancel</a></div>
    <% end %>

  </div>
</div>

</div>

app/views/posts/index.html.erb
<div class="page-wrapper">

<h2>All Posts</h2>

  <div class="offset4 pull-right">
        <%= form_tag posts_path, :method => 'get', class: "navbar-search" do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts By Title", class: 'form-control' %>
        <%= submit_tag "Search", :title => nil, class: "btn btn-primary" %>
        <% end %>
  </div>
  

  <p id="error_explanation">
  <%= flash[:notice] unless flash[:notice].blank? %>
  </p>
  
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "Title" %></th>
      <th><%= sortable "Description" %></th>
      <th>Posted By</th>
      <th><%= sortable "Created_At" %></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <a href="<%= posts_path %>/<%= post.id %>">
            <%= post.title %>
          </a>
        </td>
        <td>
            <%= h truncate(post.description, :length => 40) %></td>
        <td>
          <% if logged_in? %>
            <a href="<%= users_path %>/<%= post.user_id %>">
              <%= post.user.name unless post.user.nil?%>
            </a>
          <% else %>
              <%= post.user.name unless post.user.nil?%>
          <% end %>
        </td>
        <td><%= post.created_at.strftime("%B %d, %Y") %></td>
        
        <!--<td><a href="<%= users_path %>/<%= post.user_id %>">Show User</a></td>-->
        <!--<td><a href="#">Send Request</a></td>-->
        <!--<td><%= link_to "Delete", post, method: :delete, data: { confirm: "You sure?" } %></td>-->

      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

<br>

<% if logged_in? %>
  <%= link_to 'Create New Post!', new_post_path, class: "btn btn-primary" %>
<% else %>
<% end %>

</div>

app/views/posts/new.html.erb
<div class="page-wrapper">

<h2>Create a New Post!</h2>

<div class="create">
  <div class="container">
    
<%= render 'shared/error_messages' %>
<%= form_for(@post) do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control'%>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <br>
 
  
  <div class="actions">
    <div class="col-xs-3">
    <%= f.submit "Submit post", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<br> <br> <br> <br>
<div><%= link_to 'Back', :back, class: "btn btn-primary" %></div>

  </div>
</div>

</div>

app/views/posts/show.html.erb
<div class="page-wrapper">

<h1><%= @post.title %></h1>

<div class="col-lg-offset-4">
    <p>
        <big><strong>Title:</strong></big>
        <%= @post.title %>
    </p>
    <p>
        <big><strong>Description:</strong></big>
        <%= @post.description %>
    </p>
    <p>
        <big><strong>Posted By:</strong></big>
        <%= @post.user.name %>
    </p>
    
    <p>
        <% if logged_in? %>
            <% if current_user.id == @post.user_id %>
                <div><%= link_to "Edit Your Post", edit_post_path(@post), class: "btn btn-primary" %></div> 
            <% else %>
            <% end %>
        <% else %>
        <% end %>
        <br>
        <div><%= link_to 'Back', posts_path, class: "btn btn-primary" %></div>
    </p>
    
    
    <br><br><br>
      <div class="actions">
          <div>
            <% if logged_in? %>
                <% if current_user.id != @post.user_id %>
                    <%= link_to "I'll Help!", {:controller => "posts", :action => "send_request_mail", :id => @post.id}, class: "btn btn-primary" %>
                <% else %>
                <% end %>
            <% else %>
            <% end %>
          </div>
      </div>
</div>

</div>

app/views/posts/showMyPosts.html.erb
<div class="page-wrapper">

<h2>My Posts</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Posted By</th>
      <th>Created At</th>
      
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <a href="<%= posts_path %>/<%= post.id %>">
            <%= post.title %>
          </a>  
        </td>
        <td>
          <%= h truncate(post.description, :length => 40) %></td>
        </td>
        <td>
          <a href="<%= users_path %>/<%= post.user_id %>">
            <%= post.user.name unless post.user.nil?%>
          </a>
        </td>
        <td><%= post.created_at.strftime("%B %d, %Y") %></td>
        
        <!--<td><a href="<%= users_path %>/<%= post.user_id %>">Show User</a></td>-->
        <!--<td><a href="#">Send Request</a></td>-->
        <td><%= link_to "Delete", post, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-primary" %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

<br>

<%= link_to 'Create New Post!', new_post_path, class: "btn btn-primary" %>

</div>