config/routes.rb
Rails.application.routes.draw do

  

  root 'pages#home'
 
  get :send_request_mail, to: 'posts#send_request_mail', as: :send_request_mail
 
  get    'login'   => 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  get '/showMyPosts' => 'posts#showMyPosts'

  resources :users
  resources :posts
 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <div class="container">

	    	<p class="text-muted">&copy; 2015 Karma Inc.</p>
         <!--<%= debug(params) if Rails.env.development? %>-->
	  </div>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "KARMA", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Posts", posts_path %></li>
        <% if logged_in? %>
          <li><a href="/users">Users</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" style="display: none;">
              <li><%= link_to "My Posts", "/showMyPosts" %></li>
              <!--<li><%= link_to "My Requests", "/requests" %></li>-->
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, id: "log_out" %>
              </li>
            </ul>
          </li>
          <li class="welcome"><font color="white">Welcome <strong><%= current_user.name %></strong>!</font></li>

        <% else %>
          <%= link_to "Facebook sign in", "/auth/facebook", id: "sign_in" %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<script>
$(document).ready(function(){
  
    //$('.dropdown-toggle').dropdown()
     
    $('.navbar .dropdown').hover(function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(250).slideDown();
    }, function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(100).slideUp()
    });
})

</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Karma</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="containerLarge">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>